---

- name: Prepare localhost for Ansible usage
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Generate SSH key
      user:
        name: "{{ ansible_user_id }}"
        generate_ssh_key: yes

- name: Prepare host for Ansible usage
  hosts: all
  gather_facts: no

  roles:
    - init